### ISSUE TITLE
Bugs in dashboard

### ISSUE THREAD

**Issue by DarlannBanache** [jareer12/dynamo#2]
Hey
I've see a lot of bug into your dashboard:

First: there is 9 applications (all the same) but i've created 0
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/106172289/178104650-b8cce217-d8a6-44c3-8767-a3b270e98ede.png">

Second: There is 'too much to count' database (all the same) but i've created 0
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/106172289/178104687-8414ba59-8593-48d2-b178-aa63c2b1f12c.png">

Third: I can't edit or delete (but delete don't exist so normal) any proxy:
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/106172289/178104736-9fdb2ef1-ceb1-4352-a7e7-449dbdae7c32.png">

Have a nice day ;)

**Comment by jareer12** [comment]
It's not done yet. Still in development.
